server:
    port: 8761

app:
    id: 100018988
apollo:
    meta: http://127.0.0.1:8080
    bootstrap:
        enabled: true
        namespaces: application
        eagerLoad:
            enabled: true

spring:
    application:
        name: mockserver
    cloud:
        inetutils:
            ignoredInterfaces:
                - docker0
                - veth.*
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapping/UserMapping.xml
    type-aliases-package: com.yuyushi.mockserver.model.entity


logging:
    config: classpath:logback-boot.xml

nacos:
    config:
        server-addr: 127.0.0.1:8848
